lyonjs/lyonjs.github.com

next.config.js
pages/about.tsx
pages/index.tsx

Because warning of eslint should be fixed
- allow twitter domain (maybe we should download them and use them locally)
- use image component from next

chore: fix eslint warnings

---

data/data-override.ts

I added custom data of the last meetup.
- update data file.

feat: add data of meetup 80

---

.github/pull_request_template.md

Project without a PR template is surely a project where changes are not described correctly

chore: setup pull request template

---

.husky/pre-commit
package.json
pnpm-lock.yaml

We don't want to break CI with prettier linting error, let's fix files directly on commit with husky
Followed prettier getting started doc to setup prettier on commit with husky

chore(lint): setup husky configuration on commit action

---

CODE_OF_CONDUCT.md

Code of conduct are great, and we should define them.

docs: define basic code of conduct for source code

---

LICENSE.md

We need to define a license file
- add markdown file in root directory

chore: setup LICENSE md

---

README.md

We definitely need a better readme for this project.
With description of what is LyonJS
Contributing doc is ongoing for now
- add Readme file with badges and stuff

docs: setup a better Readme

---

modules/header/Header.tsx
modules/header/LyonJSHead.tsx
pages/about.mdx
pages/code-de-conduite.mdx

We definitely need to define the code of conduct we expect our community to respect.
- copy COC of our friends at NantesJS
- use MDX power to make this page work
- add new link in navigation
- fix typo in navigation
- handle diff title in pages a propos and COC

feat(site): add a Code of Conduct page on the website

---

CONTRIBUTING.md

We definitely need a contributing documentation if we want to have contributions.

docs: setup contributing documentation

---

.github/workflows/integration.yml

I don't want to fall in the trap of a not working code on master due to next export.
Let' s test export in CI now

chore: detect error in nextjs export in ci

---

modules/Footer.tsx
pages/_app.tsx
pages/about.mdx
pages/code-de-conduite.mdx
pages/index.tsx
styles/globals.css

For a valid sponsorship request to Vercel, we need to add the banner with an utm link on each page footer content.
- enhance app wrapper with footer and header
- modify existing pages to remove header

feat(footer): add vercel banner in footer

---

.github/workflows/build-and-deploy.yml
.github/workflows/integration.yml

We want a fast and reliable CI so let's use cache on dependencies
- modify setup pnpm and node order, use pnpm cache option
- check ci status

ci: use pnpm cache for ci performance

---

modules/header/Header.tsx
modules/header/SocialLinks.module.css
modules/header/SocialLinks.tsx
modules/header/header.module.css
modules/navigation/Navbar.module.css
modules/navigation/Navbar.tsx
modules/navigation/links/IconLink.module.css
modules/navigation/links/IconLink.tsx
modules/navigation/links/NavLink.module.css
modules/navigation/links/NavLink.tsx
modules/navigation/mobile/MobileNavigation.module.css
modules/navigation/mobile/MobileNavigation.tsx
modules/navigation/mobile/button/MobileNavigationButton.module.css
modules/navigation/mobile/button/MobileNavigationButton.tsx
modules/navigation/mobile/panel/MobileNavigationPanel.module.css
modules/navigation/mobile/panel/MobileNavigationPanel.tsx
package.json
pnpm-lock.yaml
styles/globals.css

We want to integrate the new design of the website
- update / refactor the current styles
- integrate the header for mobile and desktop
- check that the header works properly on mobile and desktop
- check the code

feat(ui): integrate the header

---

.github/workflows/playwright.yml
.gitignore
CONTRIBUTING.md
e2e/homepage.spec.ts
package.json
playwright.config.ts
pnpm-lock.yaml

We need to have more confidence on deploying modification of the website.
E2E test could help us verify that we don't break stuff.
- implement playwright simple test
- add workflow to automatically trigger E2E on PR
- add script to run test
- check CI status

test(e2e): setup e2e configuration with playwright

---

data/data-override.ts

feat(enhance): add enhanced info on event 81

---

modules/event/ActiveLink.module.css
modules/event/ActiveLink.tsx
modules/event/EventTile.module.css
modules/event/EventTile.tsx
modules/event/YearNaviation.tsx
modules/event/year-navigation.module.css
modules/navigation/Navbar.tsx
pages/evenements-precedents/[year].tsx
pages/index.tsx
styles/globals.css

We want to implement past event pages to list all the previous event of our meetup.
[Based on this mockups
](https://www.figma.com/file/XMXV8VKZEbxM5IJptBW6w4/LyonJS?node-id=0%3A1&t=YllzpLugglKe1EXu-1)
- drop past event from home page
- add events in dedicate page
- implement some event component atoms

feat: add past event page

---

modules/about/Socials.module.css

Figured out we have a bug in mobile resolution on about page
- display less social icons per row

fix(about): fix mobile display of social links in about page

---

package.json
pages/_app.tsx
pnpm-lock.yaml

We want to add tracking on lyonjs website
- use vercel analytics available with pro plan

feat: add vercel analytics to app

---

modules/event/EventCard.tsx
modules/event/EventMarkup.tsx
modules/header/LyonJSHead.tsx
modules/seo/JsonLD.tsx

Structured data will help search engine to parse meta informations contained in our website in order to display rich result to users.
It does have impact on page ranking and effectiv user actions
- define a JSONLD component for reuse purpose
- define eventMarkup component
- pass event to eventMarkup format
- export organisation object to reuse in the event
- Open preview and check that the website is displaying correctly.
- use https://search.google.com/test/rich-results?hl=fr to check for preview markup, you should see warnings but no errors.

feat(seo): add event markup inside EventCard

---

modules/event/EventCard.tsx
modules/event/EventMarkup.tsx
modules/header/LyonJSHead.tsx
modules/seo/JsonLD.tsx
pages/about.mdx
pages/code-de-conduite.mdx
pages/evenements-precedents/[year].tsx

We need dedicate metadata for each page of our website in order to make in indexed by Google/Yandex etc
- add title + description for each page of the website
- enhance markup Organisation with Orga names and pictures (Bonus points for SEO)
- refactor LyonJSHead component (use default params and allow to override them)
- handle canonical URL for SEO compliance
- add meta robots params to allow Crawler to index content
- [Une metadebugger extension and check for metadatas](https://chrome.google.com/webstore/detail/meta-debugger/jfpdemgdamgplelnlmaecbonkfgfgomp)
- check for typos in description

feat(seo): enhance LyonJSHead component

---

public/robots.txt

We need to define robots.txt file for SEO purpose
- add file manually to public folder

feat(seo): add robots.txt file in public

---

modules/meetup/api.ts
pages/evenement/[event].tsx

For #84 I wanted to optimise fetch data API call to only fetch an event and not all event for rendering a meetup detail page.
- add new graphql query / response type and service method
See that detail page are still working

refactor(fetch); fetch single meetup for event detail page

---

pages/evenement/[event].tsx

We want to correctly display markdown description in event page

feat(event): add description with markdown

---

modules/event/event-detail/EventDetail.module.css
modules/event/event-detail/EventDetail.tsx
pages/evenement/[eventSlug].tsx

In order to have the #84 ready to be merge in the first place, let's integrate a basic design to this page
- implement basic design (I know this in not complete but it is still something)

feat(design): implement basic design of event page

---

modules/meetup/api.ts
pages/evenement/[eventSlug].tsx
pages/evenements-precedents/[year].tsx

We could only fetch required information for rendering event page.
- introduce new graphql query
check that event page are still working

refactor(eventPage): fetch only a single event for rendering event page

---

modules/event/past-events/EventTile.tsx
modules/event/past-events/YearNaviation.tsx
pages/evenements-precedents/[year].tsx

Played a bit with `VoiceOver` to check what is accessible on past event page.
Face some strange issues.
- navigation is only telling years without informations
- h1 title is not very clear
- each link does not have a clear accessible label
- fix issues with better aria labels
- use voice over and play with the page

feat(past-events): enhance some a11y values

---

.github/workflows/playwright.yml
e2e/about.spec.ts
e2e/code-de-conduite.spec.ts
e2e/evenements-precedents.spec.ts
e2e/homepage.spec.ts
package.json
pages/evenements-precedents/[year].tsx
playwright.config.ts
pnpm-lock.yaml

To allow us to do some refactoring
- Run E2E on the deployed preview instead of re-running a build
- Adding E2E test for other pages

test: add e2e test for all pages

---

modules/meetup/api.ts
modules/meetup/queries/event.api.ts
modules/meetup/queries/next-event.api.ts
modules/meetup/queries/past-events.api.ts
modules/meetup/queries/years-with-meetups.ts
pages/evenement/[eventSlug].tsx
pages/evenements-precedents/[year].tsx
pages/index.tsx

To improve maintnability and to improve the separation of concern.
I split the meetup api file into dedicated query file.
I think it would be good if the PR #122 is merged first in order to be sure there is no regression

refactor: split api request in dedicated file

---

next.config.js
pages/_document.tsx

In order to improve the accessibility of the website. I add a lang attributes on the webpage
Add a lang attributes to fr on the html element

fix: add lang attribute 'fr' on html element

---

.github/workflows/build-and-deploy.yml
.github/workflows/daily-deploy.yml
.github/workflows/integration.yml

As now webssite is deployed with vercel, let's cleanup jobs to us only vercel build

chore: cleanup CI and deploy jobs

---

app/robots.ts
app/sitemap.ts
next-env.d.ts
public/robots.txt
tsconfig.json

We want to boost the SEO of LyonJS weebsite, let's generate sitemap
For now the PR is not prod ready because we use a statically generate output.
When webiste will migrate to Vercel, we will be able to use it.

feat(seo): generate sitemap dynamically

---

app/evenements-precedents/[year]/loader.tsx
app/evenements-precedents/[year]/page.tsx
modules/event/components/EventTile.module.css
modules/event/components/EventTilePlaceholder.tsx
modules/event/components/YearNavigationPlaceholder.tsx
modules/placeholder/LinePlaceholder.module.css
modules/placeholder/LinePlaceholder.tsx

Why not using suspense API to make the website UX a bit more optimistic.
Definitely wanted to play with it.
- add few component and suspense
- add some styles
had some inspiration of @m-frachet rn-placeholder ❤️ on him
Go to past event page and see the nice animation of loading

feat: add lazy loading animation

---

.npmrc

chore: fixup configuration of pnpm

---

app/layout.tsx
modules/event/components/EventCard.tsx
modules/event/components/EventTile.module.css
modules/event/types.ts
modules/meetup/queries/next-event.api.ts

Display number of going people on cta
- fix some nextjs warning on style
- value start has mixed support, flex-start is better supported
- handle new viewport export

feat(homepage): display going number on cta

---

modules/event/components/EventDetail.module.css
modules/event/components/EventDetail.tsx
modules/event/components/EventMarkup.tsx
modules/event/types.ts
modules/meetup/queries/event.api.ts
next.config.js

Let's add our picture from meetup API in event page 
- change type event
- add image
- simple image row for now.
- I may consider adding murri grid of picture 
- check event page

feat(eventPage): add pictures of event from api

---

modules/home/Number.tsx
modules/home/Numbers.module.css
modules/home/Numbers.tsx
package.json
pnpm-lock.yaml
styles/globals.css

As suggested by @jsulpis, let's add some animation on numbers
Discussed in #200 
- add motion library
- add dynamic counter logic

feat(numbers): add animation on number appear

---

data/data-override.ts

feat(replay): add replays from youtube to past events

---

app/page.tsx
modules/event/components/EventDetail.tsx
modules/home/LastReplays.module.css
modules/home/LastReplays.tsx
next.config.js
styles/globals.css

We need to show our last replays on youtube on homepage to show that we register them

feat: add replay thumbnail and link within home page

---

modules/atoms/collapsible/Collapsible.module.css
modules/home/LastReplays.module.css

- card of replays are really small on mobile device
- collapsing event detail does not work on safari Ios, we need to use polyfill for that
- [apply polyfill recommandation for collapse text](https://stackoverflow.com/questions/70897195/line-clamp-webkit-not-working-in-safari)
- enhance size of replays tiles
- use your iphone to verify

fix(homepage): fixup mobile display

---

modules/event/components/EventDetail.module.css

Event detail page have horizontal scroll on mobile because page content overflow screen width
Constraint on grid colums

fix(eventDetail): fixup mobile display

---

data/data-override.ts

feat: add new video replays about meetup 90

---

data/data-override.ts

Adding video replays about meetup 91.

feat: add new video replays about meetup 91

---

data/data-override.ts

Adding video replays about meetup 92.

feat: add new video replays about meetup 92

---

modules/event/components/EventDetail.module.css
modules/event/components/EventDetail.tsx
modules/meetup/queries/event.api.ts

feat(event): rework gallery of pictures

---

modules/event/components/EventCard.tsx
modules/event/components/EventDetail.tsx
modules/event/components/EventTile.tsx
modules/home/LastReplays.tsx
next.config.js
package.json
pnpm-lock.yaml

Let's use optimized images to make our website faster !
- install sharp as dependency
- use next image component

perfs(images): use nextjs image optimizations

---

app/layout.tsx
app/org-markup.ts

- remove useless secure as it is purely statical
- add missing info in organisation markup

fix(markup): fix organisation markup

---

app/devenir-sponsor/content.mdx
app/devenir-sponsor/opengraph-image.tsx
app/devenir-sponsor/page.tsx
app/sitemap.ts
data/schedule.ts
modules/hero/Hero.tsx
modules/hero/HeroButtonsContainer.module.css
modules/home/HomeHero.tsx
modules/icons/Gift.tsx
modules/navigation/Navbar.tsx
modules/schedule/NextSchedule.module.css
modules/schedule/NextSchedule.tsx
modules/schedule/types.ts
modules/sponsors/Sponsors.module.css
modules/sponsors/Sponsors.tsx

We want to communicate on our sponsor policy and answer to sponsor regular questions
- create dedicate page
- create custom opengraph image for it
- create component and data to display next schedules events

feat(page): add new page for sponsoring

---

app/budget-et-financement/content.mdx
app/budget-et-financement/opengraph-image.tsx
app/budget-et-financement/page.tsx
app/devenir-sponsor/content.mdx
data/budget.tsx
modules/budget/budgetTable.module.css
modules/budget/budgetTable.tsx
styles/globals.css

We want to put a page in our website to have our meetup budget publicly shared.
- add new page with a table
- MDX does not support Markdown table by default, so I used a simple html table
- go on https://lyonjs-website-git-public-budget-lyonjs.vercel.app/budget-et-financement

feat(page): add page about budget

---

.github/workflows/integration.yml
.github/workflows/playwright.yml
package.json
pnpm-lock.yaml

Upgrade to the last version of PNPM
- Add an entry `packageManager` in package.json to support corepack and remove hard coded value in github action for pnpm install as it supports this value
- update ci configuration to run pnpm 9 and node 20

chore(dep): upgrade to pnpm 9

---

data/data-override.ts

feat: add meetup 99 replays

---

data/lyonjs100-jobs.ts
modules/jobs/ListOfJobs.module.css
modules/jobs/ListOfJobs.tsx

Add Fulll jobs in jobs board for LyonJS 100 event
- Add the jobs data
- Update style to improve logo rendering
https://lyonjs-website-git-fulll-jobs-lyonjs.vercel.app/lyonjs-100

feat(lyonjs-100/jobs): add fulll jobs

---

data/lyonjs100-jobs.ts

Watch job board updates
https://lyonjs-website-git-add-kolecto-offer-lyonjs.vercel.app/lyonjs-100

feat(lyonjs100): add kolecto job offers

---

app/lyonjs-100/content.mdx
app/page.tsx
modules/lyonjs100/HomeAnnouncement.module.css
modules/lyonjs100/HomeAnnouncement.tsx

feat: some cleanup after lyonjs 100

---

.oxlintrc.json
data/data-override.ts
modules/event/components/EventDetail.tsx

feat: add meetup 102 event

---

app/evenements-precedents/[year]/page.tsx
data/data-override.ts

feat: add last meetup and static paths

---

data/schedule.ts

15th October 2025 booked by a sponsor.

feat: sponsor october 2025

---

data/data-override.ts

feat: add replays

---

data/schedule.ts

feat: add schedule sponsor

---

data/data-override.ts

feat: add replay of meetup 105
